config/routes.rb
Rails.application.routes.draw do
  get '/profile/:id', to: 'users#show', as: :profile
  devise_for :users
  patch '/avatar', to: 'users#upload_avatar'
  resources :posts do
    resources :comments, only: [:create, :index, :destroy]
    resource :likes
  end
  resources :feed, only: [:index]
  resources :relationships, only: [:create, :destroy]
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  default_scope -> { order(created_at: :desc) }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user, presence: true
  validates :post, presence:true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :image, presence: true
  validates  :image, content_type: %w[image/jpg image/jpeg image/png], size: { less_than: 3.megabytes }
  default_scope -> { order(created_at: :desc) }

  def thumbnail
    image.variant(combine_options: { resize: '500x500^', extent: '500x500', gravity: 'Center' })
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, case_sensitive: false
  has_one_attached :avatar
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id=:user_id"
    Post.where("user_id IN (#{following_ids}) OR user_id=:user_id", user_id: current_user.id)
  end


  def follow(some_user)
    following << some_user
  end

  def unfollow(certain_user)
    following.delete(certain_user)
  end

  def following?(certain_user)
    following.include?(certain_user)
  end

  def likes?(post)
    Like.exists?(user_id: id, post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.html { redirect_to @post }
        format.js { render :index }
      end
    end
  end

  def index
    @post = Post.find(params[:post_id])

    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    authorize @comment

    if @comment.destroy
      respond_to do |format|
        format.html { redirect_to @post }
        format.js
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController

  def index

    if current_user.following.exists?
      @posts = Post.where(user_id: current_user.following.pluck(:id)).order(created_at: :desc)
      return
    end

    @posts = Post.none
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @post.likes.create(user_id: current_user.id)
    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    Like.where(post_id: @post.id, user_id: current_user.id).take&.destroy
    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.limit(20)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post , flash: { success: "Post published!" }
      return
    end

    render :new, flash: { alert: "Error" }
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post

    if @post.destroy
      redirect_to profile_path(current_user)
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:image, :description)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @followed = User.find(params[:id])
    current_user.follow(@followed)
    flash[:success] = "Now following #{@followed.full_name}"
    redirect_back fallback_location: root_path
  end

  def destroy
    @followed = Relationship.find(params[:id]).followed
    current_user.unfollow(@followed)
    flash[:success] = "Stopped following #{@followed.full_name}"
    redirect_back fallback_location: root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def upload_avatar
    @user = User.find_by(id: current_user.id)
    @user.update_attributes(user_params)
    if @user.save
      redirect_back fallback_location: root_url
      flash[:success] = "Nice one!"
    end
  end

  private

  def user_params
    params.require(:user).permit(:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def get_avatar(user)
     user.avatar.attached? ? user.avatar.variant(combine_options: { resize: '256x256^', extent: '256x256', gravity: 'Center' }) : "avatar.png"
  end
end

app/views/comments/_comment_form.erb
<%= form_with(scope: :comment, url: post_comments_path(post), method: :post) do |f| %>
  <%= f.text_field :content, class: 'form-control border-0 comment-input', placeholder: 'Add a comment...' %>
  <%= f.submit 'Post', class: 'btn btn-outline-secondary btn-block' %>
<% end %>

app/views/comments/_comments.erb
<% unless post.comments.empty?  %>
<% post.comments.each do |c| %>
  <div class="row" id="comment-<%= c.id%>">
    <li class="media">
      <div class="media-left">
        <%= image_tag get_avatar(c.user), class: 'rounded-circle thumbnail' %>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= c.user.full_name %>
          <br>
          <small>
            <% if post.created_at.present? %>
              <%= distance_of_time_in_words_to_now(c.created_at) %> ago
            <% end %>
            <% if policy(c).destroy? %>
              <div class="col-3 ml-auto">
                <%= link_to fa_icon("trash"), post_comment_path(post, c), method: :delete, remote: true %>
              </div>
            <% end %>
          </small>
        </h4>
        <p><%= c.content %></p>
      </div>
    </li>
  </div>
<% end %>
<% end %>

app/views/comments/destroy.js.erb
document.getElementById('comment-<%= @comment.id %>').remove();

app/views/comments/index.js.erb
document.getElementById('comments-<%= @post.id %>').innerHTML = "<%= j render 'comment_form', post: @post %><%= j render 'comments', post: @post %>"
document.getElementById('comment_content').value = '';

app/views/feed/index.erb
<h1>Feed</h1>

<% if @posts.any?%>
  <%=  render 'posts/images' %>
  <% else %>
  <h4><%= link_to "Find some friends", root_path %> and start following them!</h4>
<% end %>

app/views/layouts/_header.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <%= link_to "Instarails", root_path, id: "logo" %>
    <button class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav navbar-right">
        <li class="nav-item <%= 'active' if params[:controller] == 'feed' %>">
          <%= link_to "Feed", feed_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if params[:controller] == 'posts' && params[:action] == 'new' %>">
        <%= link_to "New Post", new_post_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item <%= 'active' if params[:controller] == 'users' %>">
            <%= link_to current_user.email, profile_path(current_user), class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link"  %>
          </li>
          </ul>
        <% else %>
          <li class="nav-item"><%= link_to "Sign up", new_user_registration_path, class: "nav-link"%></li>
          <li class="nav-item"><%= link_to "Log in", new_user_session_path, class: "nav-link"%></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyAcademy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/_like.erb
<%= form_with model: @like, url: post_likes_path(post) do |f| %>
  <div><%= hidden_field_tag :post_id, post.id %></div>
  <%= f.button :submit, class: "btn btn-link unliked" do %>
    <%= fa_icon("heart") %>
  <% end %>
<% end %>

app/views/likes/_likes_form.erb
<div id="follow_form">
  <% if current_user.likes?(post) %>
    <%= render 'likes/unlike', post: post %>
  <% else %>
    <%= render 'likes/like', post: post %>
  <% end %>
</div>

app/views/likes/_unlike.erb
<%= form_with(model: @like, url: post_likes_path(post), method: :delete) do |f| %>
  <div><%= hidden_field_tag :post_id, post.id %></div>
  <%= f.button :submit, class: "btn btn-link liked" do %>
    <%= fa_icon("heart") %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
document.getElementById('like-<%= @post.id %>').innerHTML = "<%= j render 'unlike', post: @post %>"

app/views/likes/destroy.js.erb
document.getElementById('like-<%= @post.id %>').innerHTML = "<%= j render 'like', post: @post %>"

app/views/posts/_images.erb
<div class="card-columns">
  <% @posts %>
  <% @posts.each do |post| %>
    <div class="card">
      <div class="card-header">
        <small>
          <h6><%= post.user.full_name %></h6>
        </small>
      </div>
      <div class="card-body p-1">
        <%= link_to(image_tag(post.thumbnail, class: 'd-block w-100'), post_path(post.id)) %>
        <p class="my-1"><%= post.description %></p>
        <div class="float-left" id="like-<%= post.id %>">
          <%= render "likes/likes_form", post: post %>
        </div>
        <div class="float-right">
          <%= link_to fa_icon("comment"), "#comment-section-#{ post.id }", data: { toggle: 'collapse' }, class: "btn btn-link" %>
        </div>
        <div class="collapse" id="comment-section-<%= post.id %>">
          <div id="comments-<%= post.id %>">
            <%= render 'comments/comment_form', post: post %>
            <%= render 'comments/comments', post: post %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<h1>Latest Uploads</h1>

<% if @posts.any?%>
<%=  render 'posts/images' %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="center">
  <%= form_with(model: @post) do |f| %>
    <% if f.object.errors.any? %>
      <div class="alert alert-danger">
        <p>The following errors prevent the image from being uploaded.</p>
        <ul>
          <% f.object.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.drag_and_drop_file_field :image, 'Drag and drop image here' %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <%= f.submit 'Post', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="col-md-6 offset-md-3">
  <div class="card">
    <%= link_to profile_path(@post.user.id) do %>
      <div class="card-header">
        <ul class="list-unstyled d-flex justify-content-between">
          <li><%= image_tag get_avatar(@post.user), class: 'thumbnail-md rounded-circle' %>
          </li>
          <li><h1><%= @post.user.full_name %></h1></li>
          <br>
        </ul>
      </div>
    <% end %>
    <div class="card-header">
      <small class="float-left" id="like-<%=@post.id %>"><%= render "likes/likes_form", post: @post %></small>
      <small class="float-right">
        <% if policy(@post).destroy? %>
          <%= link_to "Delete", post_path(@post), method: :delete %>
        <% else %>
          <%= render "users/follow_form", user: @post.user %>
        <% end %>
      </small>
    </div>
    <div class="card-body">
      <%= link_to image_tag(@post.thumbnail, class: 'd-block w-100'), post_path(@post.id) %>
      <div class="card-text">
        <%= @post.description %>
        <h6 class="mb-2 text-muted text-right">
        </h6>
      </div>
      <div id="comments-<%= @post.id %>">
          <%= render 'comments/comment_form', post: @post %>
        <%= render 'comments/comments', post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/users/_follow.erb
<%= form_with(model: current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :id, user.id %></div>
  <%= f.submit "Follow", class: "btn btn-link" %>
<% end %>

app/views/users/_follow_form.erb
<div id="follow_form">
  <% if current_user.following?(user) %>
    <%= render 'users/unfollow', user: user %>
  <% else %>
    <%= render 'users/follow', user: user %>
  <% end %>
</div>

app/views/users/_unfollow.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-link" %>
<% end %>

app/views/users/show.html.erb
<div class="card w-100">
  <div class="card-header">
    <ul class="list-unstyled d-flex justify-content-between">
      <%= image_tag get_avatar(@user), class: 'rounded-circle' %>
      <h3 class="card-title align-self-center"><%= @user.full_name %></h3><br>
      <% if @user == current_user %>
        <%= link_to fa_icon("cog 2x"), edit_user_registration_path %>
      <% else %>
        <%= render 'users/follow_form', user: @user %>
      <% end %>
    </ul>
  </div>
  <div class="card-body">
    <ul class="d-flex justify-content-between">
      <li>Photos <span class="count"><%= @posts.size %></span></li>
      <li>Followers <span class="count"><%= @user.passive_relationships.count %></span></li>
      <li>Following <span class="count"><%= @user.active_relationships.count %></span></li>
    </ul>
  </div>
</div>
<%= render 'posts/images' %>